#!node

const command = process.argv[2]
const emtech = require("./lib/emtech")

async function main(){
    switch (command) {
        case "load":
            const walletId = process.argv[3]
            const amount = process.argv[4]
            console.log("paying", amount, "to", walletId, "...")
            const response = await emtech.loadWallet(process.env.INSTITUTIONAL_WALLET_ID, walletId, amount)
            console.log(response)
            break;
        default:
            console.log("v0.0.0")
    }
}

main();