#!node

const command = process.argv[2]
const emtech = require("./lib/emtech")
require("dotenv").config()

async function main(){
    switch (command) {
        case "load":
            const walletId = process.argv[3]
            const amount = process.argv[4]
            if(!amount) process.exit(1)
            console.log("paying", amount, "to", walletId, "...")
            const response = await emtech.loadWallet(walletId, amount).catch(err => console.error(`${err.response.status} ${err.response.statusText} ${err.response.data}`))
            console.log("response", response)
            break;
        default:
            console.log("v0.0.0")
    }
}

main();